config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'today#index'

  get '/welcome' => 'static#index'

  resources :today, only: :index
  resources :tags
  resources :jots, only: [:create, :edit, :show]
  resources :searches, only: [:index, :show]
  resources :archives, only: [:index, :show]
end

app/views/shared/_authentication.html.erb
<nav id='authentication' class='authentication'>
  <ul>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete  %></li>
  </ul>
</nav>

app/views/shared/_entry.html.erb
<section class='jot'>
  <h3 class='.title-without-tag'><%= jot.title_without_tag %>
    <% if jot.body.try(:size) %>
    <span class='detail fa fa-commenting-o'></span>
    <% end  %>
  </h3>

  <div class='controls'>
    <span class='edit'><a href="#" class='edit-why' id="<%= jot.id %>">why?</a>
    </span>
    <span class='edit delete'><%= link_to 'delete', jot, method: :delete %></span></h3>
    <% if jot.tag_id.present? && jot.tag.present?  %>
    <span class='tag'><%= link_to jot.tag, "/tags/#{jot.tag[1..-1]}" %></span>
    <% end %>
  </div>
  <div class='edit-box' id="edit_box_<%= jot.id %>">
    <%= form_for(jot) do |f| %>
    <div class="field">
      <%= f.text_area :body %>
      <%= f.submit 'save' %>
    </div>
    <% end %>
  </div>
</section>

app/views/shared/_entry_focus.html.erb
<section class='jot-focus'>
  <div class="cancel">x</div>
  <div class="form-contents">
    <%= form_for(@jot) do |f| %>
      <div class="field">
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.text_field :jot, autofocus: true, class: 'jot-jot', :autocomplete => :off, placeholder: "What's on your mind?"  %>
        <%= f.text_area :body, autofocus: true, class: 'jot-body' %>
      </div>
    <% end %>
  </div>
</section>

app/views/shared/_jot.html.erb
<section class='jot'>
  <h3 class='jot__title'><%= jot.title_without_tag %></h3>
  <%#= render 'shared/jot_controls', jot: jot %>
</section>

app/views/shared/_jot_controls.html.erb
<div class='controls'>
  <span class='edit'><a href="#" class='edit-why' id="<%= jot.id %>">why?</a>
  </span>
  <span class='edit delete'><%= link_to 'delete', jot, method: :delete %></span></h3>
  <% if jot.tag_id.present? && jot.tag.present?  %>
  <span class='tag'><%= link_to jot.tag, "/tags/#{jot.tag[1..-1]}" %></span>
  <% end %>
</div>
<div class='edit-box' id="edit_box_<%= jot.id %>">
  <%= form_for(jot) do |f| %>
  <div class="field">
    <%= f.text_area :body %>
    <%= f.submit 'save' %>
  </div>
  <% end %>
</div>

app/views/shared/_jot_focus.html.erb
<section class='jot-focus body' id='jot-focus'>
  <div class="modal-controls">
    <span class="close" id='jot-close-btn'>x</span>
  </div>
  <div class="jot-form">
    <%= form_for(@jot) do |f| %>
      <div class="field">
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.text_field :title, autofocus: true, class: 'title', :autocomplete => :off, placeholder: "What's on your mind?", id: 'jot-title'  %>
        <div class='jot-tips'>
          <span>hints: </span>
          <span>'enter' to save</span>
          <span>'tab' to add a body</span>
          <span>tags #</span>
          <span>reminders @</span>
        </div>
        <section class='tags'>
          <span class='tag'>#one</span>
          <span class='tag'>#two</span>
          <span class='tag'>#three</span>
        </section>
        <%= f.text_area :body, autofocus: true, class: 'jot-body', placeholder: '(body)' %>
        <%= f.submit 'save', class: 'save-button' %>
      </div>
    <% end %>
  </div>
</section>

app/views/shared/_list.html.erb
<section class='jots'>
  <% @presenter.each do |jot| %>
    <%= render 'shared/jot',  jot: jot %>
  <% end %>
</section>

app/views/shared/_nav.html.erb
<ul>
  <li><%= link_to 'today', root_path %></li>
</ul>
<hr>
<ul>
  <% @archives.each do |archive| %>
    <li><%= link_to archive, archive_path(archive) %></li>
  <% end %>
</ul>
<hr>
<ul>
  <% @tag_list.each do |tag| %>
    <li class='tag'><%= link_to tag.title_no_hash, "/tags/#{tag.title_no_hash}" %></li>
  <% end %>
</ul>

app/views/shared/_new_entry.html.erb
<%= form_for(@jot) do |f| %>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.text_area :jot, autofocus: true, class: 'jot-jot', :autocomplete => :off  %>
    <%= f.submit 'jot', class: 'jot-submit' %>
  </div>
<% end %>

app/views/shared/_new_jot.html.erb
<section class='new-jot'>
  <%= form_for(@jot) do |f| %>
    <div class="new-jot__field">
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_field :title, autofocus: true, class: 'new-jot__jot-input', :autocomplete => :off, placeholder: "what's on your mind?", id: 'new-jot__jot-input' %>
      <%#= f.submit 'jot', class: 'jot-submit' %>
      <div class="new-jot__tip" id="new-jot__tip">
        enter to save
      </div>
    </div>
  <% end %>
</section>

app/views/shared/_search.html.erb
  <%= form_tag('/searches', method: :get) do %>
    <%= text_field :search, 'search', placeholder: 'search' %>
  <% end %>

app/views/shared/_stats.html.erb
<section class='stats'>
  <span class="stats__count"><%= pluralize(@jot_count, 'jot') %></span>
  <span class="stats__count"><%= pluralize(@days, 'day') %></span>
  <span class="stats__count"><%= pluralize(@tags, 'tag') %></span>
</section>