config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'today#index'

  get '/welcome' => 'static#index'

  resources :today, only: :index
  resources :tags
  resources :jots, only: [:create, :edit, :show]
  resources :searches, only: [:index, :show]
  resources :archives, only: [:index, :show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>jots</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%#= render 'shared/authentication' %>
  <section class='l-container'>
    <%= render 'shared/jot_focus' %>
    <section class='main-content'>
        <%= yield %>
    </section>
    <nav class='control'>
      <ul class='control__actions'>
        <li id='new-jot-btn'>jot <span class='control__shortcut'>j</span></li>
        <li><%= link_to 'today', today_index_path %><span class='control__shortcut'>t</span></li>
        <li><%= link_to 'tags', tags_path %><span class='control__shortcut'>g</span></li>
        <li><%= link_to 'archives', archives_path %><span class='control__shortcut'>a</span></li>
      </ul>
    </nav>
  </section>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>jots</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class='welcome'>
  <section class='headline'>
    <h3>capsule</h3>
    <p>A spot for private thoughts, prayers, and ideas</p>
  </section>
  <div class="form">
    <%= yield %>
  </div>
</body>
</html>